services:
  db:
    image: postgres:17
    restart: always
    container_name: postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - PGPORT=${DB_PORT}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - myNetwork

  backend:
    build: 
      context: .
      dockerfile: ./django/Dockerfile
    container_name: django
    restart: always
    command: >
      sh -c "python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          gunicorn CalculationWebSite.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000
    volumes:
      - django_static_volume:/app/static
      - django_media_volume:/app/media
      - django_module_volume:/app/modules
    depends_on:
      - db
    networks:
      - myNetwork

  frontend:
    build: 
      context: .
      dockerfile: ./react/Dockerfile
    container_name: react
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - myNetwork
    
  nginx:
    build: ./nginx
    container_name: nginx
    networks:
      - myNetwork
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - django_static_volume:/home/src/app/static
      - django_media_volume:/home/src/app/media 

volumes:
  db-data:
  django_static_volume:
  django_media_volume:
  django_module_volume:

networks:
  myNetwork:
    driver: bridge