# Generated by Django 5.1.7 on 2025-05-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfield',
            name='custom_false',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productfield',
            name='custom_true',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='field_type',
            field=models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('boolean', 'Boolean'), ('select', 'Select')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.series'),
        ),
    ]
