# Generated by Django 5.1.7 on 2025-06-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='series',
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Unnamed Stock', max_length=100),
        ),
    ]
