# Generated by Django 5.1.7 on 2025-05-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
